{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gel-server.serviceAccountName" . }}
  labels:
    {{- include "gel-server.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
imagePullSecrets:
  {{- . | toYaml | nindent 2 }}
{{- end }}
